# https://taskfile.dev

version: '3'

vars:

tasks:
  run:
    deps: [build]
    cmds:
      - docker run -v raftlogs:/var/logs raft ./run.py {{.CLI_ARGS}} 
  test:
    deps: [build]
    cmds:
      - docker run raft cargo test
  check:
    cmds:
      - cargo check --target=x86_64-unknown-linux-musl
  all:
    cmds:
      - task: build:debug
      - task: publish
  build:debug:
    cmds:
      - cargo build --target=x86_64-unknown-linux-musl
      - mv target/x86_64-unknown-linux-musl/debug/raft 3700kvstore
    silent: true
  build:release:
    cmds:
      - cargo build --release --target=x86_64-unknown-linux-musl
      - mv target/x86_64-unknown-linux-musl/release/raft 3700kvstore
    silent: true
  clean:
    cmds: 
      - cargo clean
      - rm 3700kvstore
  publish:
    cmds:
      - scp 3700kvstore ameyabhat@login.ccs.neu.edu:~/networks/raft
  build:
    -  docker build -t raft:latest .
  view-logs:
    cmds:
      - docker run -v raftlogs:/var/logs raft cat /var/logs/{{.CLI_ARGS}} | bat
    interactive: true
  view-all-logs:
    cmds:
      - docker run -v raftlogs:/var/logs raft cat /var/logs/* | bat
    interactive: true
